name:                max-stock-profit
version:             0.1.0.0
github:              "@eparchas/fp-learning/max-stock-profit"
license:             BSD3
author:              "Evangelos Parchas"
maintainer:          "@eparchas"
copyright:           "2022 Evangelos Parchas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/@eparchas/fp-learning/max-stock-profit>

dependencies:
- base >= 4.7 && < 5
- split

library:
  source-dirs: src

executables:
  max-stock-profit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - max-stock-profit

tests:
  max-stock-profit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - max-stock-profit
